replicaCount: 1

image:
  repository: "random1st/mqtt-bridge"
  pullPolicy: "Always"
  tag: "latest"

forceRestart: "{{ now | quote }}"

service:
  type: ClusterIP
  port: 80

serviceMonitor:
  enabled: false
  interval: 30s

serviceAccount:
  create: true
  annotations: {}
  name: ""

existingSecret: ""

existingConfigmap: ""

config: {}
#  REMOTE_BROKER__HOST: localhost
#  REMOTE_BROKER__PORT: "8883"
#  REMOTE_BROKER__USER: "mqtt_user"
#  REMOTE_BROKER__PASS: "mqtt_password"
#  REMOTE_BROKER__TLS: "true"
#
#  LOCAL_BROKER__HOST: localhost
#  LOCAL_BROKER__PORT: "8883"
#  LOCAL_BROKER__USER: "mqtt_user"
#  LOCAL_BROKER__PASS: "mqtt_password"
#  LOCAL_BROKER__TLS: "true"
#
#  INCOMING_PATTERNS: "dev/status,qa/status"
#  OUTGOING_PATTERNS: "dev/+/cmd,qa/+/cmd"
#  LOGGING_LEVEL: "debug"
