apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt-bridge.fullname" . }}
  labels:
    {{- include "mqtt-bridge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mqtt-bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mqtt-bridge.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mqtt-bridge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}

          envFrom:
          {{- if .Values.existingSecret }}
            - secretRef:
                name: {{ .Values.existingSecret }}
          {{- else }}
            - secretRef:
                name: {{ include "mqtt-bridge.fullname" . }}-secrets
          {{- end }}