{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mqtt-bridge.fullname" . }}-secrets
  labels:
    {{- include "mqtt-bridge.labels" . | nindent 4 }}
type: Opaque
data:
  REMOTE_BROKER__HOST: {{ .Values.config.REMOTE_BROKER__HOST | b64enc }}
  REMOTE_BROKER__PORT: {{ .Values.config.REMOTE_BROKER__PORT | b64enc }}
  REMOTE_BROKER__USER: {{ .Values.config.REMOTE_BROKER__USER | b64enc }}
  REMOTE_BROKER__PASS: {{ .Values.config.REMOTE_BROKER__PASS | b64enc }}
  REMOTE_BROKER__TLS: {{ .Values.config.REMOTE_BROKER__TLS | b64enc }}

  LOCAL_BROKER__HOST: {{ .Values.config.LOCAL_BROKER__HOST | b64enc }}
  LOCAL_BROKER__PORT: {{ .Values.config.LOCAL_BROKER__PORT | b64enc }}
  LOCAL_BROKER__USER: {{ .Values.config.LOCAL_BROKER__USER | b64enc }}
  LOCAL_BROKER__PASS: {{ .Values.config.LOCAL_BROKER__PASS | b64enc }}
  LOCAL_BROKER__TLS: {{ .Values.config.LOCAL_BROKER__TLS | b64enc }}
  INCOMING_PATTERNS: {{ .Values.config.INCOMING_PATTERNS | b64enc }}
  OUTGOING_PATTERNS: {{ .Values.config.OUTGOING_PATTERNS | b64enc }}
  LOGGING_LEVEL: {{ .Values.config.LOGGING_LEVEL | b64enc }}
{{- end }}