apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-bridge.fullname" . }}
  labels:
    {{- include "mqtt-bridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "mqtt-bridge.selectorLabels" . | nindent 4 }}