name: Package and Publish Helm Chart

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Package Helm Chart
        run: |
          mkdir -p helm-repo
          helm package charts/mqtt-bridge --destination helm-repo

      - name: Update Helm repo index
        run: |
          cd helm-repo
          helm repo index . --url https://random1st.github.io/mqtt-bridge/

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./helm-repo