name: Helm Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Lint chart
        run: helm lint charts/mqtt-bridge